Repository GDGoC-Gachon/gdg-homepage-web, pull requests merged in 2025-01, with the labels that each got.

#3 [CHORE] Prettier 설정
  .github/ISSUE_TEMPLATE/project-issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .prettierignore
  .prettierrc
  .yarn/install-state.gz
  README.md
  eslint.config.js
  package.json
  postcss.config.cjs
  src/app/App.css
  src/app/App.tsx
  src/app/api.tsx
  src/app/fonts.css
  src/app/index.css
  src/app/main.tsx
  src/global.d.ts
  src/pages/MainPage.tsx
  src/shared/components/Footer.tsx
  src/shared/components/Header.tsx
  src/shared/utils/scrollToTopFunc.ts
  src/widgets/MainLayOut.tsx
  tailwind.config.js
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: ⚙️Chore

#4 [FEAT] FAQ 및 Contact 페이지 구현
  package.json
  src/app/App.tsx
  src/app/index.css
  src/pages/ContactPage/ContactPage.tsx
  src/pages/FAQPage/components/FAQButton.tsx
  src/pages/FAQPage/components/FAQToggle.tsx
  src/pages/FAQPage/constants/FAQData.ts
  src/pages/FAQPage/types/FAQItem.ts
  src/pages/FAQPage/ui/FAQPage.tsx
  src/shared/assets/icons/common/Github_logo.svg
  src/shared/assets/icons/common/Instagram_logo.svg
  src/shared/assets/icons/common/Kakao_logo.svg
  src/shared/assets/icons/common/Medium_logo.svg
  src/shared/assets/images/common/earth_logo.png
  src/shared/components/Footer.tsx
  tailwind.config.js
  yarn.lock
Labels: ✨Feature

#6 [REFACTOR] 폴더 구조 재정비
  .yarn/install-state.gz
  src/app/App.tsx
  src/features/faq/model/FAQData.ts
  src/features/faq/type/FAQItem.ts
  src/features/faq/ui/FAQButton.tsx
  src/features/faq/ui/FAQToggle.tsx
  src/pages/ContactPage.tsx
  src/pages/FAQPage.tsx
  src/shared/typings/db.ts
  yarn.lock
Labels: ♻️Refactor

#8 [FEAT] 메인 페이지 구현
  public/newsCardSample/newsCard1.png
  public/newsCardSample/newsCard2.png
  public/newsCardSample/newsCard3.png
  public/vite.svg
  src/features/main/lib/scrollToSection.ts
  src/features/main/model/NewsCardData.tsx
  src/features/main/type/NewsCardItem.ts
  src/features/main/ui/DescriptionSection.tsx
  src/features/main/ui/NewsCard.tsx
  src/features/main/ui/NewsSection.tsx
  src/features/main/ui/RecruitButotn.tsx
  src/features/main/ui/WelcomeSection.tsx
  src/pages/MainPage.tsx
  src/shared/assets/icons/main/arrow.svg
  src/shared/assets/icons/main/enter.svg
  src/shared/assets/images/main/dot.png
  src/shared/assets/images/main/mainBackground.png
  src/shared/assets/images/main/miniSquare.png
  src/shared/assets/images/main/newsCard1.png
  src/shared/assets/images/main/newsCard2.png
  src/shared/assets/images/main/newsCard3.png
  src/shared/assets/images/main/squarePattern.png
  src/shared/components/Header.tsx
  tailwind.config.js
Labels: ✨Feature

#10 [FEAT] 홈 화면 디테일 구현
  .yarn/install-state.gz
  package.json
  src/features/main/ui/DescriptionSection.tsx
  src/features/main/ui/NewsSection.tsx
  src/features/main/ui/RecruitButton.tsx
  src/features/main/ui/WelcomeSection.tsx
  src/pages/MainPage.tsx
  yarn.lock
Labels: ✨Feature
